# frozen_string_literal: true

require_relative "writer"

module Oubliette
  module Config
    # Rewrites the feature paths inside cucumber.yml.
    #
    # The file is usually hand-tuned ERB with profiles the project cares about,
    # so the original is preserved verbatim and only the path tokens are
    # substituted. When there is no cucumber.yml at all, a minimal default
    # profile is generated instead.
    class Cucumber < Writer
      register :cucumber

      CANDIDATES = %w[cucumber.yml config/cucumber.yml .config/cucumber.yml].freeze

      # cucumber-rails puts its config in config/cucumber.yml while a plain
      # cucumber project keeps it at the root, and cucumber reads whichever it
      # finds first. Rewriting the wrong one would leave the real config
      # pointing at directories that are no longer there.
      def filename
        CANDIDATES.find { |candidate| @root.join(candidate).file? } || CANDIDATES.first
      end

      def render
        path = destination("cucumber-rails")
        return nil if path.nil?

        source = original
        return generated(path) if source.nil?

        require_paths(source.gsub(%r{(?<![\w/.-])features(?=[\s/'"]|$)}, path), path)
      end
      private
        # Cucumber only auto-requires the ruby files beside a feature tree when
        # that tree sits where it expects. An explicit -r costs nothing when the
        # autoload would have worked, and is the difference between a suite and
        # a page of undefined steps when it would not.
        def require_paths(contents, path)
          contents.gsub(/^(\w[\w-]*):[ \t]*(?=\S)/) do |profile|
            line = Regexp.last_match.post_match[/.*/]
            next profile unless line.include?(path)
            next profile if line.include?("-r ")

            "#{profile}-r #{path} "
          end
        end

        def original
          source = backup_path.file? ? backup_path : @root.join(filename)
          return nil unless source.file?

          contents = source.read
          contents == Writer::ABSENT ? nil : contents
        end

        def generated(path)
          <<~YAML
            # Generated by oubliette. `rake oubliette:rollback` restores the original.
            default: --format progress --strict -r #{path}/support -r #{path}/step_definitions #{path}
            wip: --tags @wip:3 --wip #{path}
          YAML
        end
    end
  end
end
